package repository;

import Factory.SQLConnectionFactory;
import model.Employee;
import model.Position;
import org.apache.log4j.Logger;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Optional;

public class JDBCAccountRepository implements EmployeeRepository{

    private static final Logger LOG = Logger.getLogger("mts"); // singleton
    @Override
    /*Loading Employee from database*/
    public Optional<Employee> findByID(String number) {
        LOG.info("Loading employee: " + number);    //LOG for debugging
        try (Connection connection = SQLConnectionFactory.getConnection()){ //This will automatically close the connection
            String sqlCode = "select * from employees"; //SQL statement from postgres to get every column from employee table
            PreparedStatement ps = connection.prepareStatement(sqlCode); //Pre compiles the sqlcode
            ResultSet rs = ps.executeQuery(); //A table of data representing a database result set, which is usually generated by executing a statement that queries the database
            if (rs.next()) { //Checks if rs object has anything, if it does create an employee object and load all infomatin, return that employee
                Employee employee = new Employee(rs.getString("emp_name"),rs.getString("emp_id"),Position.valueOf(rs.getString("emp_position")));
                return Optional.of(employee);
            }
        } catch (SQLException e) {
            LOG.error("Error loading employee: " + number);
            e.printStackTrace();
        }
        return Optional.empty();
    }
    /*Updating employee to database*/
    @Override
    public void update(Employee employee) {
        LOG.info("Updating employee: " + employee.getEmp_ID());
        try (Connection connection = SQLConnectionFactory.getConnection()){
            String sqlCode = "update employees set emp_name=? where emp_id=?";
            PreparedStatement ps = connection.prepareStatement(sqlCode);
            ps.setString(1,employee.getEmp_Name());
            ps.setString(2,employee.getEmp_ID());
            int rows = ps.executeUpdate();
        } catch (SQLException e) {
            LOG.error("error updating emplyee: " + employee.getEmp_ID());
            e.printStackTrace();
        }
    }
}
